/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StrCalculator;

import org.junit.Test;

public class MainTest {
    @Test public void testStrCalculator() {
        StringCalculator sayH = new StringCalculator();
        sayH.greeting();
    }
}
