/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package StrCalculator;

import org.junit.Test;

public class StringCalculatorTest {
    @Test public void greeting () {
        System.out.println("Hello!");
    }
}